const imageUrl = [
  {
    id: 1,
    imageUrl: "https://source.unsplash.com/jbtfM0XBeRc",
    author: "Nazmul",
    description: "Mother, Lion, Bear, Wolf and Hen",
    time: new Date().toDateString(),
    location: "Los Angle",
    tag: "Home",
  },
  {
    id: 2,
    imageUrl: "https://source.unsplash.com/wQLAGv4_OYs",
    author: "Nazmul",
    description: "Mother, Lion, Bear, Wolf and Hen",
    time: new Date().toDateString(),
    location: "Bangladesh",
    tag: "Grace",
  },
  {
    id: 3,
    author: "Nazmul",
    description: "Mother, Lion, Bear, Wolf and Hen",
    time: new Date().toDateString(),
    location: "India",
    imageUrl: "https://source.unsplash.com/O6N9RV2rzX8",
    tag: "Family",
  },
  {
    id: 4,
    author: "Nazmul",
    description: "Mother, Lion, Bear, Wolf and Hen",
    time: new Date().toDateString(),
    location: "Dhaka",
    imageUrl: "https://source.unsplash.com/AJgFLjnmSs4",
    tag: "Love",
  },
  {
    id: 5,
    author: "Nazmul",
    description: "Mother, Lion, Bear, Wolf and Hen",
    time: new Date().toDateString(),
    location: "Rangpur",
    imageUrl: "https://source.unsplash.com/a4GET0s82rI",
    tag: "Bueaty",
  },
  {
    id: 6,
    imageUrl: "https://source.unsplash.com/1Yn4H3RgtJs",
    author: "Nazmul",
    description: "Mother, Lion, Bear, Wolf and Hen",
    time: new Date().toDateString(),
    location: "Los Angle",
    tag: "Home",
  },
  {
    id: 7,
    imageUrl: "https://source.unsplash.com/HALe2SmkWAI",
    author: "Nazmul",
    description: "Mother, Lion, Bear, Wolf and Hen",
    time: new Date().toDateString(),
    location: "Bangladesh",
    tag: "Grace",
  },
  {
    id: 8,
    author: "Nazmul",
    description: "Mother, Lion, Bear, Wolf and Hen",
    time: new Date().toDateString(),
    location: "India",
    imageUrl: "https://source.unsplash.com/IOzk8YKDhYg",
    tag: "Family",
  },
  {
    id: 9,
    author: "Nazmul",
    description: "Mother, Lion, Bear, Wolf and Hen",
    time: new Date().toDateString(),
    location: "Dhaka",
    imageUrl: "https://source.unsplash.com/_Yc7OtfFn-0",
    tag: "Love",
  },
  {
    id: 10,
    author: "Nazmul",
    description: "Mother, Lion, Bear, Wolf and Hen",
    time: new Date().toDateString(),
    location: "Rangpur",
    imageUrl: "https://source.unsplash.com/lSdKW5b4nSc",
    tag: "Bueaty",
  },
  {
    id: 11,
    imageUrl: "https://source.unsplash.com/kVCRP3uiLiE",
    author: "Nazmul",
    description: "Mother, Lion, Bear, Wolf and Hen",
    time: new Date().toDateString(),
    location: "Los Angle",
    tag: "Home",
  },
  {
    id: 12,
    imageUrl: "https://source.unsplash.com/0Sd2qqU5soQ",
    author: "Nazmul",
    description: "Mother, Lion, Bear, Wolf and Hen",
    time: new Date().toDateString(),
    location: "Bangladesh",
    tag: "Grace",
  },
  {
    id: 13,
    author: "Nazmul",
    description: "Mother, Lion, Bear, Wolf and Hen",
    time: new Date().toDateString(),
    location: "India",
    imageUrl: "https://source.unsplash.com/cn0-hgcpoL8",
    tag: "Family",
  },
  {
    id: 14,
    author: "Nazmul",
    description: "Mother, Lion, Bear, Wolf and Hen",
    time: new Date().toDateString(),
    location: "Dhaka",
    imageUrl: "https://source.unsplash.com/y6TY0wEnWqU",
    tag: "Love",
  },
];

export default imageUrl;
